# Generated by Django 4.1.3 on 2023-01-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_courses', to='students.student'),
        ),
    ]
