# Generated by Django 4.1.3 on 2022-12-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tag_alter_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
