# Generated by Django 4.1.3 on 2022-12-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag__name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
