# Generated by Django 4.1.3 on 2022-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_image',
            field=models.ImageField(blank=True, default='Images/None/sensor-img.jpg', null=True, upload_to='Images'),
        ),
    ]
